# Generated by Django 3.2.8 on 2021-10-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('R', 'Red'), ('W', 'White'), ('Y', 'Yellow')], max_length=1)),
                ('value', models.IntegerField()),
                ('updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_made', models.DateTimeField()),
                ('order_completed', models.DateTimeField()),
                ('item_type', models.CharField(choices=[('R', 'Red'), ('W', 'White'), ('Y', 'Yellow')], max_length=1)),
                ('order_status', models.IntegerField(choices=[(1, 'Order Received'), (2, 'Repository Processing'), (3, 'Shipment Processing'), (4, 'Order Completed')])),
            ],
        ),
        migrations.CreateModel(
            name='Sensory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorID', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
