# Generated by Django 3.2.8 on 2021-11-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.TextField(default='')),
                ('verification_result', models.BooleanField(default=True)),
                ('verified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
