# Generated by Django 3.2.9 on 2021-11-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='stored',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Middle'), (2, 'Right'), (3, 'Shipment'), (4, 'Completed')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='dest',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Middle'), (2, 'Right'), (3, 'Shipment'), (4, 'Completed')]),
        ),
    ]
